In [ ]:
import torch

import torch
print(torch.__version__)

In [ ]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

scalar.item()

In [ ]:
#vector
vector= torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
#REASON IT IS CAPITALED WILL BE MENTIONED LATER TO ME

MATRIX= torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
#random tensors
randomTensor = torch.rand(2,4)
randomTensor


tensor([[0.1608, 0.6764, 0.1413, 0.2244],
        [0.7582, 0.2177, 0.1277, 0.1777]])

In [ ]:
#random image tensors
randomImageTensor= torch.rand(size=(3,224,224))
randomImageTensor.shape,randomImageTensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
# creating a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creating a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
zeros.dtype

torch.float32

In [ ]:
#creating a range of tensors

a=torch.arange(0,10)
b= torch.arange(start=0,end=100, step=15)
b

tensor([ 0, 15, 30, 45, 60, 75, 90])

In [ ]:
#creating tensors like
tenZeros= torch.zeros_like(input=b)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0])

**Tensor Datatypes**

In [ ]:
x=torch.tensor([3.0,4.0,5.0],
               dtype=None)
x.dtype

torch.float32

**Important parameters while creating a tensor**

In [ ]:
x= torch.tensor([3.0,6.0,9.0],
                dtype=None, #torch.float16 = torch.half
                device=None,
                requires_grad=False)
x

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
x.dtype

torch.float16

In [ ]:
y= x.type(torch.float16)
y.dtype

torch.float16

In [ ]:
y*x

tensor([ 9., 36., 81.], dtype=torch.float16)