In [2]:
import torch

import torch
print(torch.__version__)

In [3]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

scalar.item()

In [24]:
#vector
vector= torch.tensor([[1,2,3],[2,3,4],[3,4,5]])
vector

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [29]:
vector.shape

torch.Size([3, 3])

In [6]:
#MATRIX
#REASON IT IS CAPITALED WILL BE MENTIONED LATER TO ME

MATRIX= torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX[1]

tensor([3, 4])

In [9]:
#random tensors
randomTensor = torch.rand(2,4)
randomTensor


tensor([[0.0571, 0.9252, 0.6623, 0.6578],
        [0.9179, 0.9399, 0.2261, 0.1501]])

In [10]:
#random image tensors
randomImageTensor= torch.rand(size=(3,224,224))
randomImageTensor.shape,randomImageTensor.ndim

(torch.Size([3, 224, 224]), 3)

In [11]:
# creating a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
#creating a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
ones.dtype

torch.float32

In [14]:
zeros.dtype

torch.float32

In [15]:
#creating a range of tensors

a=torch.arange(0,10)
b= torch.arange(start=0,end=100, step=15)
b

tensor([ 0, 15, 30, 45, 60, 75, 90])

In [16]:
#creating tensors like
tenZeros= torch.zeros_like(input=b)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0])

**Tensor Datatypes**

In [17]:
x=torch.tensor([3.0,4.0,5.0],
               dtype=None)
x.dtype

torch.float32

**Important parameters while creating a tensor**

In [18]:
x= torch.tensor([3.0,6.0,9.0],
                dtype=None, #torch.float16 = torch.half
                device=None,
                requires_grad=False)
x

tensor([3., 6., 9.])

In [19]:
x.dtype

torch.float32

In [20]:
y= x.type(torch.float16)
y.dtype

torch.float16

In [21]:
y*x

tensor([ 9., 36., 81.])

In [31]:
#find out details of some tensor
print(y)
print(f"Datatype of tensor: {y.dtype}")
print(f"Shape of the tensor is: {y.shape}")
print(f"Device tensor is stored on: {y.device}")

tensor([3., 6., 9.], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of the tensor is: torch.Size([3])
Device tensor is stored on: cpu


In [ ]:
#manipulating tensors // tensor operations
#subtraction
#multiplication
#division
#matrix multiplication

In [34]:
#addition
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [35]:
#multiplication
tensor= torch.tensor([[1,2,3],[4,5,6]])
tensor*10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [42]:
#subtraction
tensor= torch.tensor([1,2,3])
tensor-10

tensor([-9, -8, -7])

In [43]:
#division
tensor= torch.tensor([[1,2,3],[4,5,6]])
tensor/10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

In [40]:
#matrix multiplication
tensor= torch.tensor([[1,2,3],[4,5,6]])
tensor2= torch.tensor([[7,8],[9,10],[11,12]])
torch.matmul(tensor,tensor2)

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
#trying out pytorch inbuilt functions

torch.mul(tensor,10) #multiplication obvvvvvv
torch.add(tensor,10) #addition obvvvvvv
torch.div(tensor,10) #division obvvvvvv
torch.sub(tensor,10) #subtraction obvvvvvv

**Mainly 2 ways of performing multiplication in matrices in Deep learning**
1. Matrix multiplcation (dot product )
2. Element wise multiplication



In [41]:
#element wise multiplication
tensor=torch.tensor([1,2,3])
print(tensor,"*", tensor)
print(torch.matmul(tensor,tensor))

tensor([[1, 2, 3],
        [4, 5, 6]]) * tensor([[1, 2, 3],
        [4, 5, 6]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)