In [ ]:
import torch

import torch
print(torch.__version__)

In [ ]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

scalar.item()

In [ ]:
#vector
vector= torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
#REASON IT IS CAPITALED WILL BE MENTIONED LATER TO ME

MATRIX= torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
#random tensors
randomTensor = torch.rand(2,4)
randomTensor


tensor([[0.1608, 0.6764, 0.1413, 0.2244],
        [0.7582, 0.2177, 0.1277, 0.1777]])